language: python
python:
- '3.6'

install:
  - pip install -r requirements.txt

before_script:
  echo "kinde-courier"

script:
  - |
    set -ex
    TOX_PY="py${TRAVIS_PYTHON_VERSION/./}"
    tox
    set +x

branches:
  only:
    - master
    - auto

notifications:
  email: false

after_success:
  - codecov
